version: "3.0"
services:
  redis:
    build:
      context: ./SpringBootRedis/src/main/resources/Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  SpringBootRedis:
    build:
      context: ./SpringBootRedis/src/main/resources/Dockerfile
    ports:
      - "8085:8089"
    depends_on:
      - redis
    
volumes:
  redis-data:
